package plantuml.scenarios

import io.cucumber.java.en.Given
import io.cucumber.java.en.Then
import io.cucumber.java.en.When
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Assumptions.assumeTrue
import java.io.File

class RealLlmSteps(private val world: PlantumlWorld) {

    @Given("a real Ollama instance is running with {word} model")
    fun realOllamaInstanceIsRunningWithModel(modelName: String) {
        world.ensureOllama()
        assumeTrue(
            world.ollamaBaseUrl != null,
            "Real Ollama instance not available — skipping @realllm test"
        )
    }

    @Given("a real-llm prompt file {string} with content:")
    fun createPromptFileWithMultilineContent(fileName: String, content: String) {
        world.createGradleProject()
        world.createPromptFile(fileName, content.trimIndent())
    }

    @When("I run generatePlantumlDiagrams task with real provider {string}")
    fun runGeneratePlantumlDiagramsTaskWithProvider(provider: String) = runBlocking {
        val properties = mutableMapOf<String, String>()
        properties["plantuml.langchain4j.model"] = provider
        world.ollamaBaseUrl?.let {
            properties["plantuml.langchain4j.ollama.baseUrl"] = it
            properties["plantuml.langchain4j.ollama.modelName"] = "smollm:135m"
        }
        properties["plantuml.real.test"] = "true"
        properties["plantuml.test.mode"] = "true"

        val systemProperties = mutableMapOf<String, String>()
        world.projectDir?.let {
            systemProperties["plugin.project.dir"] = it.absolutePath
        }

        try {
            world.executeGradle(
                "generatePlantumlDiagrams",
                properties = properties,
                systemProperties = systemProperties
            )
        } catch (e: Exception) {
            world.exception = e
        }
    }

    @When("I run validatePlantumlSyntax task with real LLM")
    fun runValidatePlantumlSyntaxTask() = runBlocking {
        val properties = mutableMapOf<String, String>()
        properties["plantuml.real.test"] = "true"
        properties["plantuml.test.mode"] = "true"

        val systemProperties = mutableMapOf<String, String>()
        world.projectDir?.let {
            systemProperties["plugin.project.dir"] = it.absolutePath
        }

        try {
            world.executeGradle(
                "validatePlantumlSyntax",
                properties = properties,
                systemProperties = systemProperties
            )
        } catch (e: Exception) {
            world.exception = e
        }
    }

    @When("I run collectPlantumlIndex task with real LLM")
    fun runCollectPlantumlIndexTask() = runBlocking {
        val properties = mutableMapOf<String, String>()
        properties["plantuml.real.test"] = "true"
        properties["plantuml.test.mode"] = "true"

        val systemProperties = mutableMapOf<String, String>()
        world.projectDir?.let {
            systemProperties["plugin.project.dir"] = it.absolutePath
        }

        try {
            world.executeGradle(
                "collectPlantumlIndex",
                properties = properties,
                systemProperties = systemProperties
            )
        } catch (e: Exception) {
            world.exception = e
        }
    }

    @Then("a valid PlantUML diagram should be generated by real LLM")
    fun validPlantUmlDiagramShouldBeGenerated() {
        world.verifyDirectoryContainsFiles(
            "generated/diagrams",
            "yml",
            "A valid PlantUML diagram should be generated"
        )
    }

    @Then("a PNG image should be created by real LLM")
    fun pngImageShouldBeCreated() {
        world.verifyDirectoryContainsFiles(
            "generated/images",
            "png",
            "A PNG image should be created"
        )
    }

    @Then("embeddings should be stored in pgvector by real LLM")
    fun embeddingsShouldBeStoredInPgvector() {
        val ragDir = File(world.projectDir, "generated/rag")
        if (ragDir.exists()) {
            val ragFiles = ragDir.listFiles()
            assertThat(ragFiles).`as`("RAG directory should contain embedding files").isNotNull.isNotEmpty
        }
    }

    @Then("the prompt file should be deleted after real LLM run")
    fun promptFileShouldBeDeleted() {
        val promptsDir = File(world.projectDir, "prompts")
        if (promptsDir.exists()) {
            val promptFiles = promptsDir.listFiles()
            assertThat(promptFiles).isNullOrEmpty()
        }
    }

    @Then("the generation should complete without errors")
    fun generationShouldCompleteWithoutErrors() {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).contains("BUILD SUCCESSFUL")
    }
}
