@realllm @integration
Feature: Real LLM integration

  These scenarios exercise the plugin against a real Ollama instance.
  They are tagged @realllm and excluded from the default suite:
    ./gradlew cucumberTest -Pcucumber.tags="@realllm"

  @realllm
  Scenario: Generate a class diagram from a real Ollama model
    Given a real Ollama instance is running with smollm:135m model
    And a real-llm prompt file "class-diagram.prompt" with content:
      """
      Create a class diagram with a single class named Person
      that has two private fields: name (String) and age (Integer).
      """
    When I run generatePlantumlDiagrams task with real provider "ollama"
    Then the generation should complete without errors
    And a valid PlantUML diagram should be generated by real LLM

  @realllm
  Scenario: Validate PlantUML syntax against a real Ollama model
    Given a real Ollama instance is running with smollm:135m model
    And a real-llm prompt file "syntax-check.prompt" with content:
      """
      @startuml
      class Person {
        -name: String
        -age: Integer
      }
      @enduml
      """
    When I run validatePlantumlSyntax task with real LLM
    Then the generation should complete without errors

  @realllm
  Scenario: Collect PlantUML index against a real Ollama model
    Given a real Ollama instance is running with smollm:135m model
    And a real-llm prompt file "index-collect.prompt" with content:
      """
      @startuml
      class Person {
        -name: String
        -age: Integer
      }
      @enduml
      """
    When I run collectPlantumlIndex task with real LLM
    Then the generation should complete without errors